// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type TodoList struct {
	ListID uuid.UUID
	UserID uuid.NullUUID
	Date   time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	FirstName string
	LastName  string
}

type UserPassword struct {
	ID       uuid.UUID
	Password string
}
