// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (task_id, list_id, task_name, start_time, end_time, completion)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING task_id, list_id, task_name, start_time, end_time, completion
`

type CreateTaskParams struct {
	TaskID     uuid.UUID
	ListID     uuid.UUID
	TaskName   string
	StartTime  time.Time
	EndTime    time.Time
	Completion bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TaskID,
		arg.ListID,
		arg.TaskName,
		arg.StartTime,
		arg.EndTime,
		arg.Completion,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.ListID,
		&i.TaskName,
		&i.StartTime,
		&i.EndTime,
		&i.Completion,
	)
	return i, err
}

const getTasks = `-- name: GetTasks :many
SELECT task_id, list_id, task_name, start_time, end_time, completion from tasks 
WHERE list_id=$1
`

func (q *Queries) GetTasks(ctx context.Context, listID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.ListID,
			&i.TaskName,
			&i.StartTime,
			&i.EndTime,
			&i.Completion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
