// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: tasks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (task_id, list_id, task_name, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING task_id, list_id, task_name, start_time, end_time
`

type CreateTaskParams struct {
	TaskID    uuid.UUID
	ListID    uuid.UUID
	TaskName  string
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TaskID,
		arg.ListID,
		arg.TaskName,
		arg.StartTime,
		arg.EndTime,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.ListID,
		&i.TaskName,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
